# Добавляя, изменяя или удаляя значения не забудьте изменить сам валидатор
# @see src/Service/Validator/CarValidatorField.php
specification:
  max_speed:
    min: 100
    max: 300
  fuel:
    ['АИ-92', 'АИ-95', 'АИ-98']
  torque:
    min: 50
    max: 200
  horsepower:
    min: 80
    max: 350
  fuel_consumption:
    min: 5
    max: 35
  gear:
    ['Передний', 'Задний', 'Полный']
